name: "OOI Data Stream Repo Sync"
description: 'Github actions for syncing data stream repositories in ooi-data'
author: "lsetiawan <https://github.com/lsetiawan>"
inputs:
  GH_ORG:  # id of input
    description: 'Github Organization String.'
    required: true
    default: "ooi-data"
  GH_MAIN_BRANCH:
    description: 'Main Branch to run the workflow in.'
    required: false
    default: "main"
  DEBUG:
    description: "Debug flag. If activated, won't actually run workflow"
    required: false
    default: "false"
outputs:
  sync_status: # id of output
    description: 'Syncing Status'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "umbrella"
  color: "purple"