name: "GH Action.py"
description: 'Github actions starter for python script with container.'
author: "lsetiawan <https://github.com/lsetiawan>"
inputs:
  seconds:  # id of input
    description: 'Number of seconds to  wait'
    required: true
    default: "10"
outputs:
  time: # id of output
    description: 'The time the script finished.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "umbrella"
  color: "purple"