name: Test CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        id: action_run
        uses: ./
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          GH_ORG: ooi-data
          DEBUG: "TRUE"
      - name: Get the sync_status
        run: echo "The sync status was ${{ steps.action_run.outputs.sync_status }}"
